export const crearPiezasIniciales = () => ([
  { id: 'wr1', type: 'rook',   color: 'white', position: 'a1' },
  { id: 'wn1', type: 'knight', color: 'white', position: 'b1' },
  { id: 'wb1', type: 'bishop', color: 'white', position: 'c1' },
  { id: 'wq',  type: 'queen',  color: 'white', position: 'd1' },
  { id: 'wk',  type: 'king',   color: 'white', position: 'e1' },
  { id: 'wb2', type: 'bishop', color: 'white', position: 'f1' },
  { id: 'wn2', type: 'knight', color: 'white', position: 'g1' },
  { id: 'wr2', type: 'rook',   color: 'white', position: 'h1' },
  { id: 'wp1', type: 'pawn',   color: 'white', position: 'a2' },
  { id: 'wp2', type: 'pawn',   color: 'white', position: 'b2' },
  { id: 'wp3', type: 'pawn',   color: 'white', position: 'c2' },
  { id: 'wp4', type: 'pawn',   color: 'white', position: 'd2' },
  { id: 'wp5', type: 'pawn',   color: 'white', position: 'e2' },
  { id: 'wp6', type: 'pawn',   color: 'white', position: 'f2' },
  { id: 'wp7', type: 'pawn',   color: 'white', position: 'g2' },
  { id: 'wp8', type: 'pawn',   color: 'white', position: 'h2' },

  { id: 'br1', type: 'rook',   color: 'black', position: 'a8' },
  { id: 'bn1', type: 'knight', color: 'black', position: 'b8' },
  { id: 'bb1', type: 'bishop', color: 'black', position: 'c8' },
  { id: 'bq',  type: 'queen',  color: 'black', position: 'd8' },
  { id: 'bk',  type: 'king',   color: 'black', position: 'e8' },
  { id: 'bb2', type: 'bishop', color: 'black', position: 'f8' },
  { id: 'bn2', type: 'knight', color: 'black', position: 'g8' },
  { id: 'br2', type: 'rook',   color: 'black', position: 'h8' },
  { id: 'bp1', type: 'pawn',   color: 'black', position: 'a7' },
  { id: 'bp2', type: 'pawn',   color: 'black', position: 'b7' },
  { id: 'bp3', type: 'pawn',   color: 'black', position: 'c7' },
  { id: 'bp4', type: 'pawn',   color: 'black', position: 'd7' },
  { id: 'bp5', type: 'pawn',   color: 'black', position: 'e7' },
  { id: 'bp6', type: 'pawn',   color: 'black', position: 'f7' },
  { id: 'bp7', type: 'pawn',   color: 'black', position: 'g7' },
  { id: 'bp8', type: 'pawn',   color: 'black', position: 'h7' }
])